# Generated by Yougori. Run this project with: python yougori
import os
from pathlib import Path
import shutil
import subprocess
import sys

def main():
    executable = shutil.which("yougori.exe" if os.name == "nt" else "yougori")
    if not executable or Path(executable).resolve() == Path(__file__).resolve():
        print("Install Yougori and add its CLI to PATH, then try again.", file=sys.stderr)
        return 1
    process = subprocess.Popen(
        [executable, "launch", *sys.argv[1:]], cwd=Path(__file__).resolve().parent
    )
    while True:
        try:
            return process.wait()
        except KeyboardInterrupt:
            # The CLI receives the same console signal and owns container cleanup.
            continue

if __name__ == "__main__":
    sys.exit(main())
