import { useState } from "react"
import { cloudApi,type CloudProfile } from "@/api/cloud-api"
import { usePlatform } from "@/context/platform-context"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CloudEnvironmentDialog } from "@/components/dialogs/cloud-environment-dialog"
export function CloudDeploymentCard({environmentId}:{environmentId:string}){
  const {state,refreshPlatform}=usePlatform(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[configure,setConfigure]=useState(false),[confirmation,setConfirmation]=useState("")
  const deployment=state?.cloudDeployments?.[environmentId],env=state?.environments.find(e=>e.id===environmentId)
  if(!deployment||!env)return null
  const remove=async()=>{if(busy)return;setBusy(true);setError("");try{await cloudApi.deleteDeployment(environmentId,confirmation);await refreshPlatform();setConfirmation("")}catch(reason){setError(String(reason))}finally{setBusy(false)}}
  const action=async(value:"inspect"|"start"|"stop")=>{if(busy)return;setBusy(true);setError("");try{await cloudApi.action(environmentId,value);await refreshPlatform()}catch(reason){setError(String(reason))}finally{setBusy(false)}}
  return <section aria-label="Cloud deployment"><h3>Cloud deployment · {deployment.provider}</h3><p className="break-all text-xs">{deployment.name}</p><p className="mt-2 text-xs">{deployment.state}</p><p className="mt-2 break-all text-xs text-muted-foreground">{deployment.account} · {deployment.region}<br/>{deployment.resourceId}<br/>{deployment.address}</p><div className="mt-3 flex flex-wrap gap-2">{([['inspect','Inspect'],['start','Start VM'],['stop','Stop VM']]as const).map(([value,label])=><Button key={value} disabled={busy||deployment.state==="Deleted"} size="xs" variant="outline" onClick={()=>void action(value)}>{label}</Button>)}<Button size="xs" disabled={busy} variant="outline" onClick={()=>setConfigure(true)}>Configure SSH</Button></div><p className="mt-2 text-[10px] text-muted-foreground">VM power is separate from SSH Connect/Disconnect. Stopped cloud resources may still incur storage or network charges.</p>{deployment.state!=="Deleted"?<details className="mt-3 text-xs"><summary>Delete cloud VM</summary><p className="my-2">Permanently delete this VM and its boot disk. Existing networks, security groups, and separately attached disks remain. Type {deployment.name} to confirm.</p><Input aria-label="Cloud resource name to delete" value={confirmation} onChange={e=>setConfirmation(e.target.value)} disabled={busy}/><Button className="mt-2" size="xs" variant="destructive" disabled={busy||confirmation!==deployment.name} onClick={()=>void remove()}>Delete VM and boot disk</Button></details>:<p className="mt-2 text-xs">Cloud VM deleted. You can now remove this entry.</p>}{error||deployment.lastError?<p role="alert" className="mt-2 break-words text-xs text-destructive-foreground">{error||deployment.lastError}</p>:null}{configure?<CloudEnvironmentDialog key={environmentId} open={configure} onOpenChange={setConfigure} environmentId={environmentId} initialProfile={{name:env.name,vendor:deployment.provider as CloudProfile['vendor'],host:deployment.address,username:deployment.username}}/>:null}</section>
}
