// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest"
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react"
import { afterEach, describe, expect, it, vi } from "vitest"
import { PersonalVault } from "@/components/personal-vault"
import { vaultApi, type VaultStatus } from "@/api/vault-api"
import { listen } from "@tauri-apps/api/event"

vi.mock("@/api/vault-api", () => ({ vaultApi: { status: vi.fn(), control: vi.fn(), addItems: vi.fn(), exportPlugin: vi.fn(), create: vi.fn(), bootstrap: vi.fn(), connection: vi.fn() } }))
vi.mock("@tauri-apps/plugin-dialog", () => ({ open: vi.fn() }))
vi.mock("@tauri-apps/api/event", () => ({ listen: vi.fn(async () => () => undefined) }))
const client = { id: "client", executable: "C:\\Tools\\agent.exe", digest: "a".repeat(64), device: "Laptop", user: "SID", process: 42, environment: "Host" }
const base: VaultStatus = { running: true, locked: false, gateway: { running: true, port: 49732 }, setup: { created: true, mode: "local", hostname: "", localUrl: "http://127.0.0.1:49732/mcp", publicUrl: null }, items: [], clients: [], pending: [], activity: [] }
afterEach(() => { cleanup(); vi.clearAllMocks() })
describe("Personal Vault", () => {
  it("opens the approval panel when a background vault request arrives", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue(base)
    const focus = vi.spyOn(document, "hasFocus").mockReturnValue(false)
    render(<PersonalVault />)
    await waitFor(() => expect(listen).toHaveBeenCalledWith("vault-approval-needed", expect.any(Function)))
    const callback = vi.mocked(listen).mock.calls.at(0)?.[1]
    if (!callback) throw new Error("Vault notification listener was not installed")
    callback({ event: "vault-approval-needed", id: 1, payload: 1 })
    expect(await screen.findByRole("dialog")).toBeInTheDocument()
    focus.mockRestore()
  })
  it("connects once, hides Connect for a live tunnel, and only replaces a quick link explicitly", async () => {
    const quick = { ...base.setup!, mode: "quick" as const, publicUrl: "https://first.trycloudflare.com/mcp" }
    vi.mocked(vaultApi.status).mockResolvedValue(base)
    let finish!: (value: typeof quick) => void
    vi.mocked(vaultApi.connection).mockImplementation(() => new Promise(resolve => { finish = resolve }))
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    const connect = await screen.findByRole("button", { name: "Connect tunnel" })
    expect(screen.queryByRole("button", { name: /localhost only/i })).not.toBeInTheDocument()
    fireEvent.click(connect)
    fireEvent.click(connect)
    expect(vaultApi.connection).toHaveBeenCalledTimes(1)
    expect(connect).toBeDisabled()
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, setup: quick })
    finish(quick)
    const change = await screen.findByRole("button", { name: "Change tunnel domain" })
    await waitFor(() => expect(change).toBeEnabled())
    expect(screen.queryByRole("button", { name: "Connect tunnel" })).not.toBeInTheDocument()
    fireEvent.click(change)
    expect(vaultApi.connection).toHaveBeenCalledTimes(1)
    fireEvent.click(screen.getByRole("button", { name: "Cancel" }))
    expect(screen.queryByRole("button", { name: "Create new quick link" })).not.toBeInTheDocument()
    fireEvent.click(change)
    const replaced = { ...quick, publicUrl: "https://second.trycloudflare.com/mcp" }
    vi.mocked(vaultApi.connection).mockImplementation(async () => {
      vi.mocked(vaultApi.status).mockResolvedValue({ ...base, setup: replaced })
      return replaced
    })
    fireEvent.click(screen.getByRole("button", { name: "Create new quick link" }))
    await waitFor(() => expect(vaultApi.connection).toHaveBeenLastCalledWith("quick", "", "", false, true))
    expect(await screen.findByText(replaced.publicUrl)).toBeInTheDocument()
    expect(screen.queryByText(quick.publicUrl)).not.toBeInTheDocument()
  })
  it("restores a saved domain after reopening and offers disconnect without quick-link replacement", async () => {
    const domain = { ...base.setup!, mode: "domain" as const, hostname: "vault.example.com", publicUrl: "https://vault.example.com/mcp" }
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, setup: domain })
    vi.mocked(vaultApi.connection).mockImplementation(async () => {
      const setup = { ...domain, mode: "local" as const, publicUrl: null }
      vi.mocked(vaultApi.status).mockResolvedValue({ ...base, setup })
      return setup
    })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    fireEvent.click(await screen.findByRole("button", { name: "Disconnect tunnel" }))
    await waitFor(() => expect(vaultApi.connection).toHaveBeenCalledWith("local"))
    expect(await screen.findByLabelText("Vault hostname")).toHaveValue("vault.example.com")
    fireEvent.click(screen.getByRole("button", { name: "Close" }))
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    expect(await screen.findByLabelText("Vault hostname")).toHaveValue("vault.example.com")
    expect(screen.getByLabelText("Cloudflare tunnel token")).toHaveValue("")
    expect(screen.getByLabelText("Cloudflare tunnel token")).toHaveAttribute("placeholder", "Saved token · leave blank to reuse")
    expect(screen.queryByRole("button", { name: "Change tunnel domain" })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole("button", { name: "Quick link" }))
    fireEvent.click(screen.getByRole("button", { name: "My domain" }))
    expect(screen.getByLabelText("Vault hostname")).toHaveValue("vault.example.com")
  })
  it("keeps a failed tunnel connection retryable and shows the error", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue(base)
    vi.mocked(vaultApi.connection).mockRejectedValue(new Error("Tunnel could not connect"))
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    fireEvent.click(await screen.findByRole("button", { name: "Connect tunnel" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("Tunnel could not connect")
    await waitFor(() => expect(screen.getByRole("button", { name: "Connect tunnel" })).toBeEnabled())
  })
  it("creates the first vault explicitly and keeps agent instructions out of onboarding", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, setup: undefined })
    vi.mocked(vaultApi.create).mockImplementation(async () => {
      vi.mocked(vaultApi.status).mockResolvedValue(base)
      return base.setup!
    })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    fireEvent.click(await screen.findByRole("button", { name: "Create your personal vault" }))
    await waitFor(() => expect(vaultApi.create).toHaveBeenCalledOnce())
    expect(await screen.findByRole("region", { name: "Localhost instructions" })).toBeInTheDocument()
    expect(screen.queryByRole("button", { name: /lock vault|unlock vault/i })).not.toBeInTheDocument()
  })
  it("requires domain route confirmation and never confuses a tunnel token with an item credential", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue(base)
    vi.mocked(vaultApi.connection).mockResolvedValue(base.setup!)
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    fireEvent.click(await screen.findByRole("button", { name: "My domain" }))
    fireEvent.change(screen.getByLabelText("Vault hostname"), { target: { value: "vault.example.com" } })
    fireEvent.change(screen.getByLabelText("Cloudflare tunnel token"), { target: { value: "test-only-tunnel-token" } })
    expect(screen.getByRole("button", { name: "Connect tunnel" })).toBeDisabled()
    fireEvent.click(screen.getByRole("checkbox"))
    fireEvent.click(screen.getByRole("button", { name: "Connect tunnel" }))
    await waitFor(() => expect(vaultApi.connection).toHaveBeenCalledWith("domain", "vault.example.com", "test-only-tunnel-token", true, false))
    await waitFor(() => expect(screen.getByLabelText("Cloudflare tunnel token")).toHaveValue(""))
  })
  it("shows the actual public URL and does not include credentials in it", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, setup: { ...base.setup!, mode: "quick", publicUrl: "https://test-only.trycloudflare.com/mcp" } })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    expect(await screen.findByText("https://test-only.trycloudflare.com/mcp")).toBeInTheDocument()
    fireEvent.click(screen.getByText("How to connect ChatGPT or Claude"))
    expect(screen.getByRole("region", { name: "ChatGPT and Claude setup" })).toBeInTheDocument()
    expect(screen.queryByText(/OAuth-only connectors are not supported/)).not.toBeInTheDocument()
  })
  it("gives ready OAuth connectors distinct ChatGPT and Claude instructions with no manual client credentials", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, oauthReady: true, setup: { ...base.setup!, mode: "quick", publicUrl: "https://test-only.trycloudflare.com/mcp" } })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    fireEvent.click(await screen.findByText("How to connect ChatGPT or Claude"))
    const guide = screen.getByRole("region", { name: "ChatGPT and Claude setup" })
    expect(within(guide).getByText(/Leave Client ID and Client Secret blank/)).toBeInTheDocument()
    expect(screen.getByRole("button", { name: "Copy ChatGPT or Claude server URL" })).toBeInTheDocument()
    fireEvent.click(within(guide).getByRole("button", { name: "Claude" }))
    expect(within(guide).getByText(/Settings → Connectors → Add custom connector/)).toBeInTheDocument()
    expect(within(guide).getByText(/Leave the OAuth Client ID and Client Secret/)).toBeInTheDocument()
  })
  it("requires the broker update before offering OAuth connection instructions", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, updateRequired: true, oauthReady: true, setup: { ...base.setup!, mode: "quick", publicUrl: "https://test-only.trycloudflare.com/mcp" } })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    fireEvent.click(await screen.findByText("How to connect ChatGPT or Claude"))
    const guide = screen.getByRole("region", { name: "ChatGPT and Claude setup" })
    expect(within(guide).getByText(/Click Update vault above to activate the new MCP tools/)).toBeInTheDocument()
    expect(within(guide).queryByRole("button", { name: "Copy ChatGPT or Claude server URL" })).not.toBeInTheDocument()
  })
  it("offers a broker update instead of using the old unlock flow", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, locked: true, updateRequired: true })
    vi.mocked(vaultApi.control).mockResolvedValue({})
    vi.mocked(vaultApi.bootstrap).mockResolvedValue({ created: true, ready: true })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    const update = await screen.findByRole("button", { name: "Update vault" })
    expect(screen.queryByRole("button", { name: "Unlock vault" })).not.toBeInTheDocument()
    fireEvent.click(update)
    await waitFor(() => expect(vaultApi.bootstrap).toHaveBeenCalled())
  })
  it("explains a missing quick link during an update and shows a failed tunnel restart", async () => {
    const updating = { ...base, updateRequired: true, setup: { ...base.setup!, mode: "quick" as const } }
    vi.mocked(vaultApi.status).mockResolvedValue(updating)
    vi.mocked(vaultApi.bootstrap).mockResolvedValue({ created: true, ready: true, tunnelError: "Cloudflare could not start" })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    expect(await screen.findByText(/Your previous quick link ended when Yougori restarted/)).toBeInTheDocument()
    expect(screen.getByRole("button", { name: "Connect tunnel" })).toBeDisabled()
    fireEvent.click(screen.getByRole("button", { name: "Update vault" }))
    expect(await screen.findByRole("alert")).toHaveTextContent("Vault updated, but the public link could not be restored: Cloudflare could not start")
  })
  it("adds private items inside the vault panel", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue(base)
    vi.mocked(vaultApi.control).mockResolvedValue({})
    vi.mocked(vaultApi.bootstrap).mockResolvedValue({ created: true, ready: true })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    await waitFor(() => expect(screen.getByRole("button", { name: "Add items" })).toBeEnabled())
    fireEvent.click(screen.getByRole("button", { name: "Add items" }))
    fireEvent.change(screen.getByRole("textbox", { name: "Item name" }), { target: { value: "Work account" } })
    fireEvent.change(screen.getByLabelText("Item value"), { target: { value: "private-value" } })
    fireEvent.click(screen.getByRole("button", { name: "Save item" }))
    await waitFor(() => expect(vaultApi.addItems).toHaveBeenCalledWith([{ label: "Work account", kind: "password", resource: "", value: "private-value" }]))
    expect(vaultApi.control).not.toHaveBeenCalledWith("manage", undefined)
  })
  it("downloads a plugin ZIP only for a ready public vault", async () => {
    const { open } = await import("@tauri-apps/plugin-dialog")
    vi.mocked(open).mockResolvedValue("C:\\Users\\ExampleUser\\Downloads")
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, oauthReady: true, setup: { ...base.setup!, mode: "domain", publicUrl: "https://vault.example.com/mcp" } })
    vi.mocked(vaultApi.exportPlugin).mockResolvedValue("C:\\Users\\ExampleUser\\Downloads\\yougori-personal-vault-abcdef12.zip")
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    fireEvent.click(await screen.findByRole("button", { name: "Download plugin ZIP" }))
    await waitFor(() => expect(vaultApi.exportPlugin).toHaveBeenCalledWith("C:\\Users\\ExampleUser\\Downloads"))
    expect(await screen.findByText(/Saved to .*yougori-personal-vault-abcdef12\.zip/)).toBeInTheDocument()
  })
  it("can approve or deny a ready request inside the vault panel", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, pending: [{ id: "request", client, operation: "personal_info", title: "Share email?", description: "Return only email", allowLabel: "Approve once", ready: true, expiresAt: new Date().toISOString() }] })
    vi.mocked(vaultApi.control).mockResolvedValue({})
    vi.mocked(vaultApi.bootstrap).mockResolvedValue({ created: true, ready: true })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    const pending = await screen.findByRole("region", { name: "Pending vault requests" })
    expect(within(pending).getByText("Requests waiting for you")).toBeInTheDocument()
    expect(within(pending).getByText("Return only email")).toBeInTheDocument()
    fireEvent.click(within(pending).getByRole("button", { name: "Approve once" }))
    await waitFor(() => expect(vaultApi.control).toHaveBeenCalledWith("approve", "request"))
    fireEvent.click(within(pending).getByRole("button", { name: "Deny" }))
    await waitFor(() => expect(vaultApi.control).toHaveBeenCalledWith("deny", "request"))
  })
  it("shows vault recovery inside the app after continuing past a startup failure", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, running: false, gateway: { running: false, port: 49732 } })
    render(<PersonalVault startupError="Container disk needs recovery; Leaked cluster 15130" />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    expect(await screen.findByRole("region", { name: "Vault recovery" })).toBeInTheDocument()
    expect(screen.getByText("Start vault")).toBeInTheDocument()
  })
  it("shows masked items and explicit client revocation", async () => {
    vi.mocked(vaultApi.status).mockResolvedValue({ ...base, items: [{ id: "item", label: "Work Cloudflare", kind: "cloudflare", resource: "zone", fields: [] }], clients: [client] })
    vi.mocked(vaultApi.control).mockResolvedValue({})
    vi.mocked(vaultApi.bootstrap).mockResolvedValue({ created: true, ready: true })
    render(<PersonalVault />)
    fireEvent.click(screen.getByRole("button", { name: "Personal Vault MCP" }))
    expect(await screen.findByLabelText("Value hidden")).toBeInTheDocument()
    expect(screen.queryByRole("button", { name: /reveal|show secret/i })).not.toBeInTheDocument()
    fireEvent.click(screen.getByText("Connected agents · 1"))
    fireEvent.click(screen.getByRole("button", { name: "Disconnect and revoke agent.exe" }))
    await waitFor(() => expect(vaultApi.control).toHaveBeenCalledWith("revoke", "client"))
  })
})
